platform/net/zephyr/include/mender-net.h
platform/net/zephyr/src/mender-http.c
platform/net/zephyr/src/mender-net.c
platform/net/zephyr/src/mender-websocket.c

Added some improvements like not allocating memory for static strings, sharing adding headers to the http and websocket requests, trying multiple times to getaddr info in case the first attempt fails.

MEN-7382: Improve and optimize network connectivity code.

---

.gitignore
platform/flash/zephyr/src/mender-flash.c
tests/src/main.c

- **chore: added .DS_Store to .gitignore**
- **fix: fixed error code check for boot and flash functions**
- **chore: fixed typo in comment**
- **refac: removed unnecessary variable definition and else clause**
- **docs: added comment explaining why we check if image is confirmed**
- **chore: fixed typo in comment**
- **style: moved constant to the left side in the if condition**
- **style: removed boolean comparison with false**

Nitpicks related to platform/flash/zephyr review

---

platform/storage/zephyr/nvs/src/mender-storage.c

Ticket: None
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

fix: added missing parenthesis in if condition

---

core/src/mender-client.c

It just doesn't belong in there, it's now handled in the update module state machine as part of the DOWNLOAD and COMMIT states.
Ticket: MEN-7498

chore: Remove handling of new_provides from mender_client_authentication_work_function()

---

core/src/mender-client.c

Question: do we need to check anything else, and is it in the correct place? Is comparing the artifact type from the deployment data necessary?

Moved pending deployment

---

core/src/mender-api.c
core/src/mender-client.c

Log `No deployment available` and return MENDER_DONE on a 204 response.
Ticket: MEN-7506

fix: return `MENDER_NOT_FOUND` on 204

---

platform/tls/generic/mbedtls/src/mender-tls.c

We expect users to provide their own keys through the callback API, but for the cases when we auto-generate switch to shorter and faster ECDSA.

feat: Switch auto-generation of crypto keys to ECDSA

---

core/src/mender-client.c

Allow authentication failure if there is a pending deployment

---

add-ons/src/mender-configure.c
add-ons/src/mender-troubleshoot.c
core/src/mender-client.c
include/mender-scheduler.h
platform/log/zephyr/src/mender-log.c
platform/scheduler/posix/src/mender-scheduler.c
platform/scheduler/zephyr/src/mender-scheduler.c

Both changes are provisional and we have tasks to follow-up. See individual commits :popcorn:

Final touches for stable runtime :see_no_evil: 

---

platform/storage/zephyr/nvs/src/mender-storage.c

The pointer to the pointer will _point_ to NULL :)

fix: Correct assert on platform code

---

.check-headers-ignore
.github/workflows/check_equivalence_tests.sh
.github/workflows/check_headers.sh
core/src/mender-artifact.c
core/src/mender-client.c
core/src/mender-zephyr-image-update-module.c
include/mender-scheduler.h
include/mender-utils.h
platform/log/zephyr/src/mender-log.c
platform/net/zephyr/src/mender-net.c
platform/scheduler/posix/src/mender-scheduler.c
platform/scheduler/zephyr/src/mender-scheduler.c
platform/storage/zephyr/nvs/src/mender-storage.c
platform/tls/generic/mbedtls/src/mender-tls.c
tests/src/main.c
west.yml
zephyr/Kconfig

The main conflicts were around the state machine and the scheduler
"rewrite". I solved them by preferring the alternative scheduler,
removing the semaphore and mutexes, while keeping the update modules
state machine.

Update `feature-update_modules` from latest `main`

---

platform/log/zephyr/src/mender-log.c

chore: Use configurable buffer for logging and check logging errors.

---

core/src/mender-client.c

If `ArtifactRollbackVerifyReboot` fails, `ArtifactRollbackReboot` will be retried `CONFIG_MENDER_ROLLBACK_REBOOT_LOOP_RETRIES` times.
Ticket: MEN-7496

feat: implement ArtifactRollbackReboot retry

---

core/src/mender-client.c
core/src/mender-deployment-data.c
include/mender-utils.h
platform/tls/generic/mbedtls/src/mender-tls.c

Add transition for state loop and exit if MAX_STATE_DATA_STORE_COUNT is reached.
Ticket: MEN-7516
Changelog: Implement infinite state loop detection

feat: infinite state loop detection

---

core/src/mender-artifact-download.c
core/src/mender-artifact.c
core/src/mender-update-module.c
include/mender-artifact-download.h
include/mender-client.h
include/mender-http.h
platform/net/generic/curl/src/mender-http.c
platform/net/generic/weak/src/mender-http.c
platform/net/zephyr/include/mender-net.h
platform/net/zephyr/src/mender-http.c
platform/net/zephyr/src/mender-net.c

Artifact download refactoring follow ups

---

core/src/mender-client.c
include/mender-scheduler.h
platform/scheduler/generic/weak/src/mender-scheduler.c
platform/scheduler/posix/src/mender-scheduler.c
platform/scheduler/zephyr/src/mender-scheduler.c

Scheduler rework -- part two, work items

---

core/src/mender-artifact.c

Instead of determining the values of various meta data items for the data being processed over and over with every chunk (512 bytes) of the data, let's just do it once for every file and reuse the information for every chunk in the file. I.e. once instead of 800 times for a 400KiB artifact data file.
Ticket: MEN-7645

chore: Avoid repetitive meta data gathering for data being processed

---

core/src/mender-client.c
include/mender-scheduler.h
platform/scheduler/generic/weak/src/mender-scheduler.c
platform/scheduler/posix/src/mender-scheduler.c
platform/scheduler/zephyr/src/mender-scheduler.c

Plus one more case that we want to handle the same way.

feat: Fall back to unconditional reboot if reboot callback fails

---

.gitlab-ci.yml

Few things that I found while checking things with my QA duty hat

ci: Miscellaneous improvements

---

include/mender/update-module.h
src/core/api.c
src/core/client.c
src/platform/storage/zephyr/nvs/storage.c

These are the fixes for memory management issues (mostly leaks) that happen during new deployment checking and inventory updating. Next step (a follow-up PR) is to check and fix the ones happening during deployment download and installation.

MEN-8057: Memory management fixes (round 1)

---

src/core/client.c
src/core/deployment-data.c

This time focusing on leaks happening during a (**working**) deployment.

MEN-8057: Memory leaks fixes (round 2)

---

cmake/mender_mcu_sources.txt
src/core/api.c
src/core/client.c
src/core/inventory.c
src/include/inventory.h
src/platform/inventory/generic/weak/inventory.c
src/platform/inventory/zephyr/inventory.c
target/zephyr/Kconfig

Some basic default inventory. There's a lot of room for adding more things, but let's hope this is a good base.

MEN-7687: Default inventory

---

src/core/client.c
src/core/inventory.c

Plus one small fix in `mender_inventory_deactivate()`.

MEN-8172: Implement mender_client_deactivate()

---

docs/flashwear.md

Need some extra  :eyes:  on this
I forgot to take the deployment logs into account on my first write, but I think it's covered. Very open for suggestions if you have some

docs: document flash wear
