mendersoftware/mender-mcu

core/src/mender-client.c
The Mender Client used to check if the downloaded artifact was already installed in the past. However, this check was removed in https://github.com/mendersoftware/mender/pull/1106/commits/1fb62236abdee6d2ed2452592d289320aea1bfa5 as it prevents the use of the "Force update" option, allowing a device to take part in the same deployment twice. Today, all the "already-installed" logic is performed in the backend.
Ticket: MEN-7428
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
=> feat: do not check if artifact is already installed

core/src/mender-api.c, include/mender-api.h
=> feat: implemented API POST v2 device/deployments/next

platform/storage/zephyr/nvs/src/mender-storage.c
According to the API docs, `nvs_read` returns the number of bytes read. There is no explicit mention that a return of 0 can be interpret as "not found".
Maybe it worked for some specific platforms if the driver(s) were implemented with this in mind, but generally speaking we should accept also `ENOENT`.
=> fix: Interpret also `ENOENT` error as not found

.gitlab-ci.yml, CMakeLists.txt, core/src/mender-api.c, core/src/mender-artifact.c, core/src/mender-utils.c, platform/tls/generic/mbedtls/src/mender-tls.c
- **fix: compiler warning -Werror=unused-function**
- **fix: compiler warning -Werror=sign-compare**
- **fix: compiler warning -Werror=pointer-sign**
- **fix: compiler warning -Werror=pointer-arith**
- **fix: compiler warning -Werror=implicit-function-declaration**
- **build: added option to enable all warnings as errors**
- **test: enabled all warnings as errors in smoke test**
=> Fixed compiler warnings

core/src/mender-client.c
If we fail to store deployment data, we should fail early.
Ticket: MEN-7436
=> fix: Don't run the REBOOT state callback if there was a failure before

platform/storage/zephyr/nvs/src/mender-storage.c
At least for the ESP driver, a `nvs_read` from a NULL pointer gives I/O error, even when `len` is set to 0. My understanding of the API docs is that it should not be the case, but my painfully slow discovery tells otherwise.
Workaround this by allocating 1 byte first for the peek read.
Changelog: None
Ticket: None
=> fix: Workaround I/O errors on some NVS drivers

core/src/mender-artifact.c
Replaced multiple calls to `sscanf` with `strtoull` in mender artifact parsing, because the calls to `sscanf` resulted in unexplained segmentation faults on some hardware.
=> fix: replaced sscanf with strtoull

platform/storage/posix/src/mender-storage.c
On success, `fread()` return the number of items read. This number equals the number of bytes transferred only when size is 1. Hence, we should check that 1 item is read instead of N Bytes.
=> fix: fixed error check when reading state

core/src/mender-client.c
So that the newly flashed image can be marked as `pending` in the install step (which happens _after_ the flashing is completed).
See https://github.com/mendersoftware/mender-mcu/blob/a948a58e7f300ed202b07559cda69e697758330f/core/src/mender-client.c#L1219-L1228
This reverts commit 86a2594c0550f0559360fb40050c90b468fd4172.
The original commit was addressing a segfault in a failure scenario, which we might need to fix independently. This commit at least ensures that "the happy path" works :)
=> fix: Keep the flash handle alive after closing

platform/net/zephyr/src/mender-net.c, zephyr/Kconfig
The secondary is optional, and it is meant for the cases where the Artifacts are downloaded from a different server (or rather, a server that needs a different CA)
=> feat: Support for two CA certificates

core/src/mender-artifact.c, include/mender-utils.h
On ESP32 Extensa, the sizeof size_t is 4 bytes, which was making the first assert(s) fail. Use `unsigned long` instead.
And the second assert(s) where also crashing, I think it's  because `strcmp` will not stop comparing until getting the null byte...
=> fix: Fix asserts from Artifact parsing

core/src/mender-client.c
It has never belonged into
mender_client_authentication_work_function(), must have slipped in there as part of some rebase/conflict resolution.
Ticket: MEN-7481
=> fix: Move the call of mender_inventory_activate() into mender_client_activate()

core/src/mender-client.c, include/mender-storage.h, platform/storage/posix/src/mender-storage.c, platform/storage/zephyr/nvs/src/mender-storage.c
Handle unsupported artifact types when we 1) load a saved state and 2) when we get a new deployment.
=> Handle unsupported artifact types

platform/storage/zephyr/nvs/src/mender-storage.c
Accidentally removed in de0fab1def36c91e65000727e4d7c251dd09a7b2.
=> fix: Restore mender_save/get_update_state() for Zephyr

platform/storage/zephyr/nvs/src/mender-storage.c
By adding explicit pointer casts and amending a typo.
Additionally, add a `const` qualifier for the save method.
=> fix: Fix Zephyr platform code for save/load state

include/mender-utils.h
Fixes warning in Zephyr builds
```
/home/lluis/west/modules/mender-mcu/zephyr/../include/mender-utils.h:52: warning: "ARG_UNUSED" redefined
```
Previously defined in Zephyr toolchain:
* https://github.com/zephyrproject-rtos/zephyr/blob/v3.7.0/include/zephyr/toolchain/gcc.h#L263
=> chore: Guard definition of `ARG_UNUSED`

README.md
Updated Mender Artifact command in README.md to use zephyr-image as artifact type.
=> docs: updated mender artifact command in README.md

core/src/mender-client.c
Print (at info level) progress every 10%. At most 10 log lines.
=> chore: Improve download progress logs

platform/storage/zephyr/nvs/src/mender-storage.c
We need to cast to `void * ` the _address_ of `state`.
=> fix: Fix (more) platform code for update state storage

core/src/mender-zephyr-image-update-module.c, include/mender-utils.h
Renamed `ARG_UNUSED` to `MENDER_ARG_UNUSED` not to mess with Zephyr's definition of `ARG_UNUSED`. Also renamed `NDEBUG_UNUSED` to `MENDER_NDEBUG_UNUSED` to conform to `MENDER_` prefix.
=> chore: added MENDER_ prefix to ARG_UNUSED and NDEBUG_UNUSED

CMakeLists.txt, core/src/mender-api.c, core/src/mender-artifact.c, core/src/mender-client.c, core/src/mender-deployment-data.c, core/src/mender-inventory.c, core/src/mender-utils.c, include/mender-deployment-data.h, include/mender-flash.h, include/mender-update-module.h, include/mender-utils.h, platform/flash/posix/src/mender-flash.c, platform/flash/zephyr/src/mender-flash.c, platform/scheduler/posix/src/mender-scheduler.c, platform/scheduler/zephyr/src/mender-scheduler.c, platform/storage/zephyr/nvs/src/mender-storage.c, platform/tls/generic/mbedtls/src/mender-tls.c, tests/src/main.c, zephyr/CMakeLists.txt
- Created deployment data management API.
- Added deployment data version number which allows us to
add/remove/modify fields in the future.
- Added the deployment data store counter field that prevents infinite
reboots.
- Deployment data is now validated when reading or writing from store.
- Also did some preparation for adding the update state field later in
MEN-7515.
=> feat: added deployment data version number and store counter

platform/log/zephyr/src/mender-log.c
To ease developers to further investigate the issues, let's allow logging functionality back in `main`.
=> chore: Enable again logging

zephyr/CMakeLists.txt
Only the zephyr-image Update Module makes use of it (plus we have a plan to merge these code bases, see MEN-7554).
Without this fix, we cannot build the project on a board not supporting integration with MCUBoot bootloader.
=> MEN-7529: Compile `mender-flash.c` only when update module is enabled

platform/net/zephyr/src/mender-http.c
MSEC_PER_SEC doesn't seem to be defined anywhere. Let's just use good old numbers nad set the timeout to 60 seconds.
Ticket: MEN-7531
=> fix: HTTP request timeout

core/src/mender-client.c, core/src/mender-deployment-data.c, include/mender-deployment-data.h, include/mender-storage.h, platform/storage/posix/src/mender-storage.c, platform/storage/zephyr/nvs/src/mender-storage.c
Removed the key and corresponding functions for storing the update_state
and the artifact type. It is now a part of the deployment data.
Ticket: MEN-7515
=> fix: store state in deployment data

platform/net/zephyr/src/mender-http.c
All sorts of things can fail in an HTTP request.
Ticket: MEN-7531
=> chore: Improve the HTTP request error log message

core/src/mender-client.c, platform/scheduler/zephyr/src/mender-scheduler.c
- **chore: make declaration of symbols static**
- **chore: fixed non-ANSI function declarations**
- **chore: fixed unused variable 'status' in non-debug**
=> Fixed some warnings revealed in static checks

CMakeLists.txt, core/src/mender-artifact.c, core/src/mender-client.c, include/mender-artifact.h, include/mender-sha.h, platform/sha/generic/mbedtls/src/mender-sha.c, platform/sha/generic/weak/src/mender-sha.c, zephyr/CMakeLists.txt, zephyr/Kconfig
This was a bit harder than I first anticipated. Enjoy 🍿🍻 
```
$ west flash && west espressif monitor
---snip---
Hello World! esp32s3_devkitc/esp32s3/procpu
---snip---
[00:01:01.395,000] <dbg> mender: mender_log_print: mender_artifact_check_integrity (223): Checking integrity for artifact file 'header.tar'
[00:01:01.395,000] <dbg> mender: mender_log_print: mender_artifact_check_integrity (223): Checking integrity for artifact file 'data/0000/zephyr.signed.bin'
[00:01:01.395,000] <dbg> mender: mender_log_print: mender_artifact_check_integrity (223): Checking integrity for artifact file 'version'
---snip---
[00:01:04.243,000] <inf> mender: Artifact installation done, rebooting
---snip---
This shit works baby! esp32s3_devkitc/esp32s3/procpu
---snip---
[00:00:20.187,000] <inf> mender: …
```
=> Implemented artifact integrity checks

core/src/mender-artifact.c, core/src/mender-utils.c, include/mender-utils.h
We have seen sscanf() causing hard failures on real HW, at least on the ESP32-based ones. Let's avoid it in favor of our simple and fast code.
Ticket: MEN-7562
=> fix: Introduce mender_utils_hexdump_to_bytes() and use it in checksum verification

core/src/mender-api.c
Clears `clang` warning:
```
.../mender-api.c:250:9: error: variable 'provides' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
250 |     if (NULL == cJSON_AddStringToObject(json_provides, "device_type", mender_api_config.device_type)) {
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_null.h:26:14: note: expanded from macro 'NULL'
26 | #define NULL ((void*)0)
|              ^
.../mender-api.c:302:35: note: uninitialized use occurs here
302 |     mender_utils_free_linked_list(provides);
|                                   ^~~~~~~~
.../mender-api.c:250:5: note: remove the 'if' if its condition is always false
250 |     if (NULL == …
```
=> chore: Move variable declaration so that its always initialized at END

core/src/mender-deployment-data.c
Was overlooked when adding state to the deployment data.
Ticket:None
=> chore: validate state in deployment data

platform/net/zephyr/src/mender-net.c, platform/storage/zephyr/nvs/src/mender-storage.c, target/zephyr/Kconfig
This is almost the same as just enabling the CRC option, so my only motivation for doing this is that it might be possible that you for some reason don't want a CRC on all the data in the NVS? If that's not a concern, the alternative to this is to simply enable `CONFIG_NVS_DATA_CRC` , which will then write and verify a CRC for all data elements in the nvs.
=> MEN-7517: Ensure atomicity/consistency of saved state data

core/src/mender-inventory.c, platform/scheduler/zephyr/src/mender-scheduler.c
Based on #105 
Regarding the locking part -- to the best of my knowledge, the only part that needs locking is authentication (and `artifact_name` as @lluiscampos pointed out) which is out of scope of this PR.
=> Scheduler rework -- part three, inventory and locking

west.yml
The module didn't receive updates during these months of development so we can stick to this version for now.
=> chore: Pin the `cjson-zephyr` dependency to the latest commit

core/src/mender-client.c
From something like:
```
[00:01:22.304,412] <inf> mender: Downloading deployment artifact with id '5f1aab23-9
629-46e1-b13e-b80033470902', artifact name 'nrf-update-inventory' and uri...
```
To something like:
```
[00:02:33.102,996] <inf> mender: Downloading artifact with id '5cb9365...', name 'nr
f-update-giving', uri 'https://c271964d41749feb10da762816c952ee.r2.cloudf...
```
So that at least part of the uri is visible.
=> chore: Shorten the downloading artifact log entry

target/posix/CMakeLists.txt
=> chore: Disable building of MbedTLS tests and utilities

platform/net/zephyr/src/mender-net.c
Was overlooked in 5a1e18b2b4a6d817137b20556363c5b0a010fb92
=> fix: rename leftover  mender_utils_strbeginwith to  mender_utils_strbeginswith

core/src/mender-artifact.c, platform/net/generic/curl/src/mender-http.c, platform/net/zephyr/src/mender-http.c
* We don't care if the files _inside_ a payload are compressed, we only want to check for compressed artifacts, i.e. that the payload is not compressed.
* Moved the check to `artifact_read_manifest` to avoid having to call it for every file.
* Check the return value of `artifact_download_callback`
Ticket: MEN-7594
=> fix: allow compressed files inside a payload

README.md
At least for me, running as root and installing pkg-config was necessary. I used Ubuntu 24.
=> chore: Fixed instructions for POSIX build on Debian / Ubuntu

core/src/mender-api.c, core/src/mender-utils.c, include/mender-utils.h
So that it doesn't end up on the stack.
Also change the type of the `str` field to `const char *` because it always points to string literals.
=> fix: Make the mapping in mender_utils_http_status_to_string() static

include/mender-log.h, platform/log/zephyr/src/mender-log.c
Zephyr logging is a complex thing that does a lot of magic and optimizations. Using the macros from one place with a single '%s' argument leaves no room for magic. By using the macros directly from various places in our sources and with the various arguments, we give the magic a chance to happen.
This makes **zero** difference in how things work (or rather doesn't) on my ESP32-EVB board. The only difference is that I now see the full URL:
```
[00:00:09.878,000] <inf> mender: Downloading artifact with id 'f47ef20...', name 'update56', uri 'https://c271964d41749feb10da762816c952ee.r2.cloudflarestorage.com/mender-artifacts-us/66eaa007a9b44e490044b0f5/d1758124-ab9d-4e8f-b05a-1d511d29826c?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=a848c3308d7d52663bbd129dff6a18b7%2F20241122%2Fus-east-1%2 …
```
=> chore: Use Zephyr logging macros directly

core/src/mender-api.c, core/src/mender-client.c, core/src/mender-zephyr-image-update-module.c, include/mender-flash.h, include/mender-utils.h, platform/flash/generic/weak/src/mender-flash.c, platform/flash/posix/src/mender-flash.c, platform/flash/zephyr/src/mender-flash.c, platform/tls/generic/mbedtls/src/mender-tls.c
I didn't know if we wanted to fail on everything except `204`, so I added `MENDER_ABORTED`. If we can go to failure on everything except a `204`, then we could just check for `MENDER_FAIL`
I also added a check to reboot just in case you abort right after the check in install
=> fix: fail deployment when it's aborted

core/src/mender-artifact.c
Checking `*ch != '\0'` in the loop condition doesn't work because by the time we do it `ch` is one byte/character futher because of the for-loop increment.
Ticket: none
=> fix: Fix buffer overflow when removing ".tar" from a checksum file name

core/src/mender-artifact.c
Tested with
```
diff --git a/core/src/mender-artifact.c b/core/src/mender-artifact.c
index c46920c..7c3ae46 100644
--- a/core/src/mender-artifact.c
+++ b/core/src/mender-artifact.c
@@ -304,6 +304,7 @@ mender_artifact_create_ctx(size_t buf_size) {
mender_log_error("Unable to allocate memory for artifact context");
return NULL;
}
+    mender_log_info("Starting with a buffer size of %zd", buf_size);
if (NULL == (ctx->input.data = malloc(buf_size))) {
mender_log_error("Unable to allocate memory for artifact context buffer");
free(ctx);
@@ -360,6 +361,7 @@ mender_artifact_process_data(mender_artifact_ctx_t *ctx, void *input_data, size_
/* Copy data to the end of the internal buffer */
if ((NULL != input_data) && (0 != input_length)) {
if ((ctx->input.length + input_length) > ctx->input.size) { …
```
=> Fix: header.tar checksum calculation in chunks

target/zephyr/Kconfig
After analyzing the worst-case stack scenarios for all functions on arm using `puncover`, we discovered the highest worst-case stack usage was at 2,328 bytes. Since `puncover` doesn't support xtensa architecture, we estimated the worst-case scenarios for xtensa in two ways: 1) caluclating the average increase in stack sizes of functions from arm
to xtensa - which was at ~56%
2) getting the max of the increase percentage. Two functions had a 300%
(8 -> 32 bytes), but considering that is way above average, it made
more sense to disregard the extreme outliers; the next highest, which had
quite a few entries, was at 100%
Considering a 100% increase in some functions, the worst case would be around ~4.6 kB in xtensa.
6 kB should therefore be sufficient, as it allows the worst case sizes in arm …
=> chore: set default work queue stack-size to 6 kB #12

README.md
Requires https://github.com/mendersoftware/mender-mcu-integration/pull/37
=> docs: Update Zephyr version to 4.0.0 and remove stable branch policy

platform/scheduler/zephyr/src/mender-scheduler.c
=> fix: Add missing `#include` for sys_reboot() on Zephyr

cmake/mender_mcu_sources.txt, core/src/mender-api.c, core/src/mender-client.c, core/src/mender-inventory.c, include/mender-os.h, platform/os/generic/weak/src/mender-os.c, platform/os/posix/src/mender-os.c, platform/os/zephyr/src/mender-os.c
Things like `mender_scheduler_mutex_create()` and
`mender_scheduler_reboot()` look/sound quite confusing even though, strictly speaking, both mutual exclusion and reboot are related to scheduling.
Ticket: none
=> chore: Rename mender-scheduler to mender-os and adapt function names

.gitlab-ci.yml
The two variables are needed when we eventually want to add the coverage for the integration tests to mender-mcu
=> Set variables and stage in trigger job

core/src/mender-deployment-data.c
Some of the fields in deployment data are initialized to `null` because they are populated later from other places. Not allowing `null` values in such fields thus means that freshly created and initialized deployment data is not valid until those fields are populated. The data is validated every time we try to store it in non-volatile memory so it either needs to never be saved until being fully populated or we need to consider not-fully-populated deployment data valid. However, since the state of the client is saved as part of the deployment data, the latter approach is required because otherwise we can't even save the client's state in some cases.
Ticket: MEN-7934
=> fix: Allow `null` values in deployment data

core/src/mender-client.c
The first commit is from #143, only the last two commits are relevant for this PR.
=> Fix: Fail deployment in case of checksum mismatch

.gitlab-ci.yml
If we manually trigger a pipeline on a PR branch,
`CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_SHA` will be empty, resulting in the downstream pipeline to fail.
Furthermore, specifying which revision of mender-mcu to use, is done by selecting which branch to run the pipeline for. Since we need the sha to be able to checkout PR branches in mender-mcu-integration, we can simply always set `MENDER_MCU_REVISION` to the sha of the latest commit.
Add a description to the variables you can modify to make it easier when manually creating pipelines.
=> ci: use `CI_COMMIT_SHA` as default value for `MENDER_MCU_REVISION`

include/mender/client.h, src/core/client.c
`malloc_func` and `realloc_func` got a `mender_` prefix accidentally in some mass rename/change.
Ticket: none
=> chore: Rename the `allocation_funcs.` fields in `mender_client_config_t`

include/mender/utils.h, src/include/utils.h
We want to mark the callbacks in mender-mcu-integration main as weak to allow redefinition in the integration tests, see: https://github.com/mendersoftware/mender-mcu-integration/commit/6f6fb37bec396d8aaa71173796b68c9a0c70b17e
=> chore: move `MENDER_FUNC_WEAK` to public API

src/core/client.c
Useful when doing the state machine tests
=> chore: add debug log when entering download state

src/core/deployment-data.c, target/zephyr/Kconfig
I mainly want this in order to exit earlier when doing the state transition tests, but I think it makes sense to let it be configurable anyways.
=> chore: make max state data counter configurable

src/core/artifact.c, src/core/client.c, src/include/artifact.h, tests/unit/core/artifact_test.cpp
We shall check `version` and `header.tar` as soon as they are fully downloaded, so that the rest of the download can be aborted if the integrity of any of these is compromised.
Implemented by splitting the integrity checks into individual items (to be used during header parsing) and the remaining ones (to be used after the payload(s) have been downloaded).
=> MEN-8075: Do early integrity checks for the non-payload items

src/core/client.c
This is more of a suggestion and something that comes from me working on state machine tests.
I have relied on using `MENDER_UPDATE_STATE_END` as a way to know when when the state transitions are over. Unifying the flow to always go (some flow)->`MENDER_UPDATE_STATE_CLEANUP`->`MENDER_UPDATE_STATE_END`, instead of having exceptions for certain states, makes it a bit easier.
Let me know if it makes sense.
=> chore: always go cleanup->end in download state

src/core/client.c, src/include/client.h
The logging will go from:
`Inside work function [state: 1]`
to
`Inside work function [state: MENDER_CLIENT_STATE_OPERATIONAL]`
=> chore: log client states with names instead of numbers

src/core/client.c
I think this was suggested to me when I added the log to the download state, but nevertheless, this should ensure that we always get the `Entering state...` logs which the state-machine tests are created around
=> chore: always log which state we enter

target/zephyr/Kconfig
You can now easily select which Mender server to use in the Kconfig, by choosing between:
* hosted Mender EU
* hosted MENDER US
* on-prem
Ticket: MEN-8080
=> chore: add server-options to Kconfig

src/core/client.c, target/zephyr/Kconfig
I forgot to remove the `default "..."` in the previous PR, resulting in the server host being set to `...` by default
=> chore: don't set default server host to `...`

src/core/api.c, src/platform/storage/zephyr/nvs/storage.c
In case the artifact name is not known (e.g. the initial state of a device until the first successful deployment), the string `"unknown"` is returned. We need to cache this value to fix two issues:
1. Make it cached and avoid trying to read it and fail again and again and
2. avoid memory leaks when the callers of the `mender_storage_get_artifact_name()` function get a `const` pointer and don't `free()` it
Ticket: MEN-8056
=> fix: Cache `"unknown"` as artifact name

.gitlab-ci.yml
Move away from the deprecated `cpp-coveralls`, and use coveralls own tool `coveralls-reporter`.
Make the report parallel so we can combine reports from mender-mcu-integration
=> ci: update coverage job

.gitlab-ci.yml
Coveralls has different branches, but currently a new PR won't create a new branch, which means all coverage will be pushed to main branch
=> Specify coveralls branch name

src/platform/net/zephyr/http.c
Zephyr OS HTTP client code already adds its own `Host:` HTTP header on the requests, which results in our HTTP requests having a duplicated header.
See:
* https://github.com/zephyrproject-rtos/zephyr/blob/v4.0.0/subsys/net/lib/http/http_client.c#L595
While some servers accept this (for example hosted Mender API Gateway) others error with 400 Bad request. In other words it is an invalid behaviour tolerated in some servers, so better to just clean it up.
=> MEN-8203: Remove duplicated `Host` HTTP header on HTTP requests

src/core/api.c
Check the return value from `ensure_authenticated_and_locked()` and return `MENDER_FAIL` on failures to authenticate.
Ticket: MEN-8219
=> fix: return `MENDER_FAIL` if authentication fails

README.md, src/platform/storage/posix/storage.c, src/platform/storage/zephyr/nvs/storage.c, target/posix/CMakeLists.txt, target/zephyr/CMakeLists.txt, target/zephyr/Kconfig, target/zephyr/mender-artifact.cmake
Integrate with CMake build system so that a Mender Artifact is generated next to the Zephyr kernel and its byproducts.
For the most simple use case, only the Artifact Name needs to be specified, the  rest are optional or have sane default values. This policy imitates the design of other Mender build integrations, like Yocto or mender-convert.
TODO:
=> MEN-8102: Generate the Mender Artifact as part of the Zephyr build byproducts

src/platform/net/zephyr/net.c
Prints `errno = Software caused connection abort` instead of `ernno = 11`
=> chore: log errno with strerror()

cmake/CMake_posix_defaults.txt, cmake/CMake_weak_defaults.txt, cmake/mender_mcu_sources.txt, src/core/client.c, src/include/certs.h, src/platform/certs/generic/weak/certs.c, src/platform/certs/posix/certs.c, src/platform/certs/zephyr/certs.c, target/zephyr/CMakeLists.txt, target/zephyr/Kconfig
Suggestion for how to add the dormant/backup certificate. I didn't think it made sense to add it to `mender-mcu-integration`. Either way, we'll create a follow-up ticket for actually testing the X2 certificate, as it turned out to be non-trivial to create a server with that specific root ca
=> feat: added dormant certificate

include/mender/utils.h, src/core/api.c, src/core/client.c, src/core/utils.c, src/include/os.h, src/platform/os/generic/weak/os.c, src/platform/os/posix/os.c, src/platform/os/zephyr/os.c, tests/unit/core/utils_test.cpp
=> MEN-8223: Avoid committing aborted deployment

src/core/inventory.c
This is to avoid logging `mender: Failed to get provides from storage` on a fresh device
=> chore: don't log error if provides is not found

.gitlab-ci.yml
To make build safer within our own runner
Ticket: QA-866
=> ci: switch from public to GCP runners

.gitlab-ci.yml
Remove the now deprecated custom parser in favor of the new linter, which aligns to the new release process.
Note that we keep the sign-off checker until we resolve QA-1046.
=> QA-1032: Replace commit linter

target/zephyr/Kconfig
The secondary CA cert is really optional, as a custom Mender Server could use the same domain for both API calls and Artifacts storage.
Set `MENDER_NET_CA_CERTIFICATE_TAG_SECONDARY_ENABLED` default to `n` and instead select it when selecting hosted Mender option(s).
=> MEN-8351: fix(build): Set default value for secondary CA cert to false + misc
